### ISSUE TITLE
Questions about long video generation

### ISSUE THREAD

**Issue by liutaocode** [bendanzzc/AnimateAnyone-reproduction#17]
Recently, I have been curious about the challenge of generating long videos.

The paper for AnimateAnyone indicates that it builds upon EDGE (Editable dance generation from music) (Section 4.1 in https://arxiv.org/pdf/2311.17117.pdf). Nonetheless, EDGE requires retraining of an editing network to create the second half of the video using the first half as a base (Figure 4 in https://arxiv.org/pdf/2211.10658.pdf). This process is quite complex, as it involves retraining an editing network

Although the official code is not released, some third party has their ways of generating long videos. For example, MooreThreads generates long videos by interpolate_latents ( [Code](https://github.com/MooreThreads/Moore-AnimateAnyone/blob/02a4342b17fe58a18a196f12eb702c50978456b7/src/pipelines/pipeline_pose2vid_long.py#L560)) and it can generates 128 frames in default.  Open-AnimateAnyone seems the same thing by smoothing the latent ([Code](https://github.com/guoqincode/Open-AnimateAnyone/blob/f3e014e0c985cd06e1955169cb381aa61482a968/demo/gradio_pipeline.py#L256)) In your code, I can also see the average operation ([Code](https://github.com/bendanzzc/AnimateAnyone-reproduction/blob/8ab089e092bb23c6ca331e2259742f40701cf835/pipeline_stable_video_diffusion_controlnet_long.py#L603)).

From the information provided, it seems that the methods may differ from those described in the original paper. The official demo appears to perform well, particularly in complex backgrounds, in contrast to third-party releases, which could play a significant role in the final results.

Here are my questions:

What is your opinion on the challenge of generating long videos? Do you believe it is necessary to train a similar editing network? Thank you for the discussion.

**Comment by bendanzzc** [comment]
Thank you for your summary. I have learned a lot. I am sorry, because my main purpose is not research, but implementation, so I may not have a deep understanding of the principles of these different methods. However, intuitively, the effect of all model-based post-processing should theoretically be better than that of non-model-based methods. But when it comes to implementation, the indicators are not only about performance improvement, but also about business benefits and the cost of time and resources invested. Therefore, for me, this point is not particularly important.

Based on my experience, a simple idea is similar to the sd-inpainting-lagency in the diffusers library, which can fix the content of the first x frames and generate the content of the next T-x frames, but the effect is similar to what is currently used. I can attach the code for reference. the reference [code](https://github.com/huggingface/diffusers/blob/v0.22.3/src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint_legacy.py#L502) may help.

Thanks for you sharning.

**Comment by liutaocode** [comment]
Thanks for sharing. I will check the code : )
